### ISSUE TITLE
[Bug] safari text element can not be layouted properly when transform is changed

### ISSUE THREAD

**Issue by Moon-DaeSeung** [moonmoonbrothers/uglychart#149]
https://github.com/moonmoonbrothers/uglychart/assets/64200419/f07b7394-5f69-4a66-9185-56d71bfa6f4c

**Comment by wool0826** [comment]
뭔가 다른 기능들에도 유사한 이슈가 있는데, 가장 마지막 요소에만 애니메이션이 적용된다는 공통점이 있는 듯

**Comment by Moon-DaeSeung** [comment]
https://github.com/moonmoonbrothers/uglychart/issues/153

마지막요소에만 애니메이션이 적용되는 문제는 여기에 기술했습니당
